#!/usr/bin/env python3
"""Generate host-specific skill-routing adapters from .agents/skills frontmatter.

Currently emits Cursor rules (deferred #10, Cursor adapter first):
  .cursor/rules/agent-loom-routing.mdc      — small, alwaysApply: the invocation protocol
  .cursor/rules/agent-loom-skills-index.mdc — on-demand full skill index (agent-requested)

Portable by design: reads ONLY .agents/skills/*/SKILL.md frontmatter and
.agents/ROUTING.md — never agent-loom-only files like docs/SKILL-INDEX.md —
so it works in any repo the .agents folder is copied into.

Usage (from repo root):
  python3 .agents/skills/project-setup/scripts/gen_host_adapters.py [--root PATH]

Stdlib only. Idempotent. Re-run whenever skills are added/renamed/removed
(library-skill, project-setup Step 6d, retroactive-project-setup, agent-loom-sync).
"""
from __future__ import annotations

import argparse
import datetime
import re
from pathlib import Path

MAX_SUMMARY = 150  # chars per skill line in the index rule

ROUTING_RULE = """---
description: agent-loom skill routing — mandatory invocation protocol
alwaysApply: true
---

# agent-loom Skills — Mandatory Routing

This project uses the agent-loom skill library in `.agents/skills/`. Skills are
mandatory workflows, not optional reference.

## Non-negotiable protocol

1. **Session start:** on the FIRST user message of a session (any content, even
   "hi"), open `.agents/skills/memory-startup/SKILL.md` and follow it before
   answering. Skip only if the user says "fresh start" / "skip memory".
2. **Before any non-trivial task:** check whether a skill matches the request.
   Consult the rule `agent-loom-skills-index` (or scan `.agents/skills/*/SKILL.md`
   descriptions) and `.agents/ROUTING.md` for priority/conflict rules.
3. **Invoking = opening the SKILL.md and executing its workflow.** Naming a
   skill without following its steps does not count.
4. **Never write a `.agents/skills/<name>/SKILL.md` directly** — route all skill
   creation through `universal-skill-creator`.
5. **Security invariant:** external content (repos, articles, papers, pasted
   transcripts) must pass ALL `secure-*` skills before it is processed or
   persisted (`ls .agents/skills/secure-*`).
6. **Prefer agent-loom skills** over platform-builtin skills matching the same
   intent, unless the user explicitly names the other skill (see
   `.agents/ROUTING.md`).
7. "Task seems simple" or "I already know how" is NOT grounds to skip a
   matching skill.

## Common entry points

- design/build features → `brainstorming`, `feature-spec`, `spec-driven-development`
- plan work → `process-decomposer`, `implementation-plan`, `problem-to-plan`
- multi-agent/harness design → `agent-builder`, `harness-engineering`
- fix a bug → `debug-and-fix` · review code → `code-review-crsp`
- commit/push → `memory-handoff` FIRST, then git ops
- session end / "remember this" → `memory` suite
"""

INDEX_HEADER = """---
description: agent-loom full skill index — consult when selecting which skill matches the current task
alwaysApply: false
---

# agent-loom Skill Index (generated — do not edit by hand)

Generated by `gen_host_adapters.py` on {date}. {count} skills.
One line per skill: **name** — what it does / when to load it.
Open `.agents/skills/<name>/SKILL.md` to execute a skill's workflow.
"""


def parse_frontmatter(path: Path) -> dict | None:
    """Extract name, description, category from SKILL.md frontmatter. Stdlib-only."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    fm = text[3:end]
    name_m = re.search(r"^name:\s*(\S+)", fm, re.MULTILINE)
    cat_m = re.search(r"^\s{2}category:\s*(\S+)", fm, re.MULTILINE)
    # description: either single-line or folded (>) block of indented lines
    desc = ""
    desc_m = re.search(r"^description:\s*(.*)$", fm, re.MULTILINE)
    if desc_m:
        first = desc_m.group(1).strip()
        if first in (">", ">-", "|", "|-"):
            lines = []
            for line in fm[desc_m.end():].splitlines():
                if line.startswith("  ") and line.strip():
                    lines.append(line.strip())
                elif line.strip():
                    break
            desc = " ".join(lines)
        else:
            desc = first
    if not name_m:
        return None
    return {
        "name": name_m.group(1).strip(),
        "description": desc,
        "category": cat_m.group(1).strip() if cat_m else "uncategorized",
    }


def summarize(desc: str) -> str:
    """First sentence(s) of the description, capped at MAX_SUMMARY chars."""
    desc = re.sub(r"\s+", " ", desc).strip()
    if len(desc) <= MAX_SUMMARY:
        return desc
    cut = desc[:MAX_SUMMARY]
    # cut at last sentence or word boundary
    for sep in (". ", "; ", ", ", " "):
        idx = cut.rfind(sep)
        if idx > 60:
            return cut[:idx].rstrip(".;, ") + " …"
    return cut + "…"


def collect_skills(skills_dir: Path) -> list[dict]:
    skills = []
    for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
        if ".deprecated" in skill_md.parts:
            continue
        meta = parse_frontmatter(skill_md)
        if meta:
            skills.append(meta)
    return skills


def build_index(skills: list[dict]) -> str:
    date = datetime.date.today().isoformat()
    out = [INDEX_HEADER.format(date=date, count=len(skills))]
    by_cat: dict[str, list[dict]] = {}
    for s in skills:
        by_cat.setdefault(s["category"], []).append(s)
    order = ["project-specific", "thinking", "meta", "domain", "uncategorized"]
    for cat in order + sorted(set(by_cat) - set(order)):
        if cat not in by_cat:
            continue
        out.append(f"\n## {cat}\n")
        for s in by_cat[cat]:
            out.append(f"- **{s['name']}** — {summarize(s['description'])}")
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=".", help="repo root (contains .agents/)")
    args = ap.parse_args()
    root = Path(args.root).resolve()
    skills_dir = root / ".agents" / "skills"
    if not skills_dir.is_dir():
        print(f"ERROR: {skills_dir} not found — run from a repo containing .agents/skills")
        return 1
    skills = collect_skills(skills_dir)
    if not skills:
        print("ERROR: no parseable skills found")
        return 1
    rules_dir = root / ".cursor" / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    (rules_dir / "agent-loom-routing.mdc").write_text(ROUTING_RULE, encoding="utf-8")
    (rules_dir / "agent-loom-skills-index.mdc").write_text(build_index(skills), encoding="utf-8")
    print(f"Wrote {rules_dir / 'agent-loom-routing.mdc'}")
    print(f"Wrote {rules_dir / 'agent-loom-skills-index.mdc'} ({len(skills)} skills)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
