"""Per-skill Red Flags registry for universal-skill-creator curation."""

from __future__ import annotations

RED_FLAGS: dict[str, list[str]] = {
    "adversarial-hat": [
        "Generic critique without named failure mode or evidence",
        "Phase 3 run before Phase 1 foundations are challenged",
        "Solutions critiqued without testing problem-solution fit",
        "Critique stops at timeline noise instead of core assumptions",
    ],
    "agent-builder": [
        "Topology designed without checking platform parallel limits",
        "Single agent shipped with no role prompt or skill stack",
        "Scaffold choice ignored despite large benchmark variance",
        "Fan-out merge has no explicit output contract between agents",
    ],
    "agent-launcher": [
        "Parallel agents spawned with hidden data dependencies",
        "Sequential chain assumes implicit handoff between agents",
        "Spawn attempted before prompt files exist on disk",
        "Subagent scope lacks explicit file boundaries",
    ],
    "agent-loom-sync": [
        "Whole-tree rsync with delete on .agents/skills/",
        "Local-only skill missing from protected list in plan",
        "Forked skill overwritten without user opt-in",
        "Upstream path points at wrong repo or missing .agents/skills",
    ],
    "agent-system-architecture": [
        "Shared blackboard without staleness or versioning rules",
        "Parallel agents write to overlapping output paths",
        "External tool calls lack per-agent rate-limit budgets",
        "Termination criteria undefined — no owner decides done",
    ],
    "api-and-interface-design": [
        "Undocumented quirks left as implicit caller contracts",
        "Validation duplicated in every internal function",
        "PUT used for partial updates instead of PATCH",
        "List endpoints return unbounded arrays without pagination",
    ],
    "api-deprecation-and-migration": [
        "Sunset announced without working replacement and docs",
        "Breaking change shipped in patch or minor version",
        "Dual-write path has no reconciliation or drift checks",
        "Deprecation timeline set without consumer usage evidence",
    ],
    "app-security-hardening": [
        "Frontend-only validation treated as sufficient",
        "Multi-tenant query missing account or tenant constraint",
        "Secrets or tokens logged in error or debug output",
        "External JSON trusted without schema or type validation",
    ],
    "apply-paper-to-project": [
        "Paper ingested directly instead of via learn-from-paper",
        "Codebase refactored before reading AGENTS.md and architecture",
        "Technique applied beyond what evidence supports",
        "Paper benchmark context assumed to match project scale",
    ],
    "architectural-decision-log": [
        "ADR written retrospectively with confabulated rationale",
        "Rejected alternatives omitted from the record",
        "Accepted status used with no revisit or supersede path",
        "Decision recorded without observable enforcement hook",
    ],
    "assumption-mapping": [
        "Risks listed instead of testable assumptions",
        "Demand-layer assumptions skipped for tech-heavy ideas",
        "More than 15 assumptions mapped in one pass",
        "Assumption has no linked validation or kill criterion",
    ],
    "brainstorming": [
        "Design section combined with unresolved approach question",
        "Multiple questions asked in a single message",
        "Existing codebase ignored before proposing new structure",
        "Direction chosen without user agreement on approach",
    ],
    "browser-testing-with-devtools": [
        "UI fix claimed done without browser verification",
        "Personal browser profile used on untrusted pages",
        "Page-context JS mutates state without explicit approval",
        "Stale service worker cache masks whether fix works",
    ],
    "business-modeling": [
        "Full BMC used when Lean Canvas fits earlier uncertainty",
        "VPC filled without confirmed segment or problem fit",
        "Canvas treated as validation with zero customer evidence",
        "Revenue model assumed without pricing or willingness signal",
    ],
    "ci-cd-and-automation": [
        "CI commands diverge from local lint/test/build scripts",
        "Runtimes and action versions left unpinned",
        "Branch protection missing — CI is advisory only",
        "Secrets committed or inlined in workflow YAML",
    ],
    "code-review-crsp": [
        "Review produced on empty diff without scope confirmation",
        "Test file changes skipped or given superficial pass",
        "Large rename treated as logic change without diff-filter",
        "Findings lack severity and concrete remediation",
    ],
    "code-simplification": [
        "Simplification required test changes that alter behavior",
        "Well-named helper inlined for fewer lines only",
        "Nested ternaries introduced to reduce line count",
        "Refactor bundled unrelated behavior changes",
    ],
    "codebase-understanding": [
        "utils/ or helpers/ named as architecture without reading code",
        "Monorepo mapped from single entry point only",
        "Generated artifacts included in architecture map",
        "Dependency graph inferred without reading imports",
    ],
    "compress-skill": [
        "secure-* skill compressed instead of split at 180 lines",
        "Description triggers removed during compression",
        "Content moved to references/ without load trigger",
        "CORE workflow steps deleted to hit line budget",
    ],
    "context-engineering": [
        "Context gathered by guessing instead of repo evidence",
        "Irrelevant files included that dilute the task signal",
        "Constraints unnamed so violations go unnoticed",
        "Assumptions presented as facts without confirmation path",
    ],
    "create-agent-prompt": [
        "Role prompt written as global system identity",
        "Prompt filled with vague be-helpful noise",
        "Agent boundary overlaps another agent without flagging",
        "Success handoff omits what to pass and to whom",
    ],
    "cross-link-skills": [
        "Description edited to remove skill names used as triggers",
        "Examples rewritten to break illustrative skill references",
        "Functional invoke links stripped from workflow steps",
        "Call graph updated without checking reverse references",
    ],
    "customer-discovery": [
        "Interviews designed to validate instead of learn",
        "Future-tense hypotheticals treated as evidence",
        "No currency question on past spend or workaround effort",
        "Kill signal ignored because interview felt positive",
    ],
    "debug-and-fix": [
        "Fix applied against minified path without source mapping",
        "Linear ticket claims accepted without codebase verification",
        "Suite green but reproduction test does not exercise bug",
        "Root cause declared before minimal repro exists",
    ],
    "deep-thinking": [
        "Framework chosen before problem diagnosis",
        "Socratic and adversarial-hat combined in one session",
        "Pre-mortem run after commitment already made",
        "Session ends without one concrete next action",
    ],
    "deprecate-skill": [
        "Deprecation without grepping callers across SKILL.md files",
        "Skill archived but surviving skill description not updated",
        "Migration path missing for merged trigger phrases",
        "Call graph left pointing at .deprecated/ skill",
    ],
    "design-direction": [
        "Single safe direction presented without exploration",
        "Directions differ on fewer than three dimensions",
        "Hybrid direction committed instead of one clear posture",
        "Non-technical owner given options without a recommendation",
    ],
    "design-review": [
        "Generic praise instead of scoring against direction brief",
        "Contrast judged by eyeball instead of APCA script",
        "Finding vague — no specific token or component target",
        "Accessibility issues noted without measurable failure",
    ],
    "design-system": [
        "DESIGN.md generated without reading DIRECTION.md first",
        "Multiple competing token sources instead of one canonical file",
        "Interactive states missing hover/active/disabled variants",
        "Icons or fonts shipped without license or attribution check",
    ],
    "eval-judge": [
        "Longer response scored higher without length bias check",
        "Confident tone rewarded over factual accuracy",
        "Pairwise compare run as two independent absolute scores",
        "Judge model changed without recalibrating on known-bad cases",
    ],
    "eval-output": [
        "Scoring performed without an explicit rubric",
        "Single overall score hides dimensional tradeoffs",
        "Numeric score assigned before written justification",
        "Two outputs compared via duplicate solo evaluations",
    ],
    "eval-pipeline": [
        "Flaky eval treated as one-off instead of tracked over time",
        "Judge or rubric change without regression on bad cases",
        "LLM judge run on 100% traffic with no sampling plan",
        "Pipeline green while dimension-level failures are hidden",
    ],
    "eval-rubric-design": [
        "Accuracy dimension undefined for the task context",
        "High aggregate score masks low business-critical dimension",
        "Fluency overweighted versus completeness or safety",
        "Rubric criteria not observable from output alone",
    ],
    "experiment-backlog": [
        "Backlog item missing funnel surface or hypothesis sentence",
        "High ICE item kept despite hard feasibility failure",
        "ICE scores self-inflated without anchor to past wins",
        "Retention experiment listed without long-running holdout plan",
    ],
    "experiment-readout": [
        "Analysis proceeds despite failed SRM check",
        "Significant language used for Directional decision class",
        "Primary win declared while guardrail metric breached",
        "Instrumentation drift mid-test ignored in validity review",
    ],
    "experiment-runbook": [
        "Exposure event fires on flag fetch not variant render",
        "Custom exposure captured without PostHog $feature_flag_called",
        "B2B test assigns at person level instead of account group",
        "Runbook shipped without rollback or kill-switch steps",
    ],
    "experiment-spec": [
        "Decision class missing from line one of the spec",
        "Hypothesis not falsifiable — no if-clause decision rule",
        "MDE stated as absolute percent instead of relative lift",
        "Exposure defined as flag fetch not user-visible variant",
    ],
    "experimentation": [
        "Decision class retrofitted after results are known",
        "Orchestrator analyzes results instead of routing to readout",
        "A/B chosen for persistent treatment needing holdout design",
        "Primary metric or guardrails declared post-launch",
    ],
    "feature-spec": [
        "Spec drifts into HOW — stack or file paths in requirements",
        "Acceptance criteria not testable as written",
        "Edge cases omitted that block spec-crosscheck coverage",
        "Needs Clarification list left non-empty at approval",
    ],
    "fermi": [
        "Most uncertain factor not identified or bounded",
        "Estimate presented for legal or budget commitment",
        "Independent approaches disagree by order of magnitude unresolved",
        "Population or rate assumptions stated without source",
    ],
    "first-principles": [
        "Rebuild step skipped after assumptions identified",
        "Legal or regulatory constraints dismissed as conventional",
        "Prior art ignored instead of questioned with reasons",
        "Output lists assumptions without reconstructed approach",
    ],
    "frontend-design": [
        "UI coded before design-direction commitment exists",
        "Components built from memory not golden examples",
        "Raw hex or magic numbers bypass DESIGN.md tokens",
        "Data surface missing loading empty or error states",
    ],
    "generate-changelog": [
        "Every commit listed verbatim instead of grouped themes",
        "Breaking changes buried below Changed section",
        "Internal refactors or CI fixes listed as user-facing",
        "Version bump inconsistent with semver of actual changes",
    ],
    "git-workflow-and-versioning": [
        "All work squashed into one commit losing slice narrative",
        "Formatting-only changes mixed with behavior commits",
        ".env or secrets committed before gitignore exists",
        "Conventional commit type mismatches actual change nature",
    ],
    "idea-evaluation": [
        "Composite score treated as verdict over distribution wedge",
        "Monetisation deferred for revenue-dependent viability",
        "GO issued with founder-market-fit score of one unmitigated",
        "Kill criteria from evaluation ignored after low score",
    ],
    "idea-generation": [
        "Ideas filtered during generation instead of after batch",
        "User's killed-but-haunting lead not explored",
        "Schlep-blind ideas dismissed without second look",
        "Batch lacks diversity across domains or problem types",
    ],
    "implementation-plan": [
        "Plan reads like PRD with user stories not tasks",
        "Phase one cannot produce any demoable vertical slice",
        "Horizontal layering plan — all DB then all API",
        "Plan omits explicit files and verification per phase",
    ],
    "improve-skills": [
        "Gotchas moved to references/ away from pre-encounter path",
        "Description rewrite removed existing trigger phrases",
        "External pattern applied before secure-* SAFE clearance",
        "Delegated link claimed where output transform is required",
    ],
    "incremental-implementation": [
        "Slice shipped without tests while later slices depend on it",
        "While-I-am-here refactor bundled into feature slice",
        "Long-lived branch used instead of flag for partial UX",
        "Slice boundary unclear — spans unrelated subsystems",
    ],
    "inversion": [
        "Inverted finding has no concrete preventive action",
        "Obvious pre-known failures listed without deeper push",
        "Inversion used where pre-mortem or adversarial fits better",
        "Success criteria never stated before failure flip",
    ],
    "knowledge-graph": [
        "Full graph rebuild run before query_graph for relational ask",
        "Inferred edges override authoritative Calls: from SKILL-INDEX",
        "Repo walk skipped — partial graph presented as complete",
        "graph.json stale versus latest handoff not rebuilt",
    ],
    "learn-from": [
        "Sub-skill credibility gate skipped before application",
        "External content applied before all secure-* skills pass",
        "Repo guardrail silently overwritten by external pattern",
        "Multiple sources merged without per-source security scan",
    ],
    "learn-from-article": [
        "Eng blog scale advice applied without user scale context",
        "Medium or dev.to piece taken as fact without evidence",
        "Best-practices list adopted without production proof",
        "Article fetched and persisted before secure-* SAFE",
    ],
    "learn-from-chat": [
        "Skill or memory updated without explicit user approval",
        "One-off project quirk captured as global learning",
        "Learning added to skill already at 200 lines without swap",
        "User preference recorded as systematic skill gap",
    ],
    "learn-from-paper": [
        "arXiv preprint accepted without peer or citation scrutiny",
        "SOTA claim used without checking newer superseding work",
        "Methodology flaws ignored due to venue prestige",
        "Paper PDF ingested before secure-* content scan",
    ],
    "learn-from-repo": [
        "Star count used as quality proxy without reading source",
        "README patterns adopted without verifying in code",
        "Repo conventions copied as universal without context check",
        "Repo code executed during learning instead of read-only",
    ],
    "library-skill": [
        "Scan aborted at zero skills without path verification",
        "Category read from wrong frontmatter nesting level",
        "Reference index wiped on partial or failed run",
        "Changelog skill path assumed wrong directory name",
    ],
    "memory": [
        "Global memory appended while file over budget",
        "Secrets tokens or credentials written to memory files",
        "External content pasted verbatim as durable policy",
        "Orchestrator sub-skill invoked without routing need",
    ],
    "memory-audit": [
        "Audit deletes entries without explicit user request",
        "Suspected injection handled without secure-* scan",
        "Full session logs loaded instead of routed slices",
        "Audit report omits stale or superseded status flags",
    ],
    "memory-capture": [
        "Raw long transcript captured instead of summarized note",
        "Capture written directly to global without promote path",
        "Secrets or credentials included in captured note",
        "Capture lacks provenance or source attribution",
    ],
    "memory-compact": [
        "Append to over-budget file without compacting first",
        "Active decisions or revisit triggers deleted during compact",
        "Global memory compacted without user approval",
        "Provenance stripped when merging duplicate entries",
    ],
    "memory-decision": [
        "Decision logged without revisit trigger or explicit none",
        "Old decision overwritten instead of superseded link",
        "Deferred item recorded as rejected decision",
        "Rationale duplicated in handoff instead of decision-log link",
    ],
    "memory-forget": [
        "User deletion request overridden for convenience",
        "Index still references forgotten entry paths",
        "Decision rationale deleted when archival was safer",
        "Forget run without checking downstream handoff refs",
    ],
    "memory-handoff": [
        "Handoff exceeds 80-line budget",
        "Secrets tokens or raw private data in handoff body",
        "Long decision rationale pasted instead of log link",
        "Git state omitted from handoff next-agent context",
    ],
    "memory-promote": [
        "Low-confidence maybe promoted to global memory",
        "Internal URLs or private project facts promoted globally",
        "Global memory used as unstructured journal dump",
        "Promote executed without user intent confirmation",
    ],
    "memory-recall": [
        "Full agent-handoffs or session-log loaded by default",
        "Superseded decision presented as current policy",
        "Stale memory cited without flagging uncertainty",
        "Recall bypasses MEMORY-ROUTING intent table",
    ],
    "memory-startup": [
        "Every memory file loaded ignoring MEMORY-ROUTING",
        "Superseded decision treated as active without status check",
        "Global memory skeleton created without user intent",
        "Cold-start skipped on bare greeting first message",
    ],
    "ooda": [
        "Stuck in Orient debating meaning while action delayed",
        "Observe step skipped — acting on assumptions only",
        "OODA loop never closes with explicit Act step",
        "Competitive response modeled as static not adaptive",
    ],
    "performance-optimization": [
        "Optimization started without baseline measurement",
        "CSS or frontend tuned while DB is actual bottleneck",
        "Multiple changes shipped — win cannot be attributed",
        "Synthetic score improved but real-user metrics flat",
    ],
    "prd-writing": [
        "PRD drafted without discovery or evidence section",
        "Out of scope section empty or missing",
        "Requirements stated as untestable aspirations",
        "PRD marked Approved on first draft without iteration",
    ],
    "pre-mortem": [
        "Obvious failure cause avoided because it feels embarrassing",
        "Pre-mortem run mid-execution after commitment locked",
        "Failure causes blame people instead of systems",
        "Mitigations listed without owner or timeline",
    ],
    "problem-to-plan": [
        "TODO tasks not self-contained for isolated agent execution",
        "Broad feature request forced into narrow change-spec",
        "Change-spec written as full feature-spec with FR/NFR bloat",
        "Success criteria missing from every TODO item",
    ],
    "process-decomposer": [
        "Triage read only first process volume not all",
        "Partial cluster match treated as exact process hit",
        "skill-chain task launched outside project-orchestrator",
        "Decomposition skips triage on complex multi-skill request",
    ],
    "product-soul": [
        "PMF lens skipped — interest conflated with retention",
        "Strategy claims no named competitor or alternative",
        "GTM reduced to marketing tagline without channel mechanism",
        "User described as demographic not situational person",
    ],
    "project-constitution": [
        "Rule stated as preference — routinely waived in practice",
        "Unenforceable rule like code should be clean",
        "Constitution changed without version bump and amendment",
        "Spec approved against outdated constitution version",
    ],
    "project-orchestrator": [
        "Single-skill request over-orchestrated with subagents",
        "Subagent spawned without explicit file boundaries",
        "AGENTS.md Orchestration Map not read before routing",
        "Process-backed entry ignored for novel decomposition",
    ],
    "project-setup": [
        "AGENTS.md generated without interview step",
        "Orchestration Map auto-generated without milestone context",
        "Skill gaps not mapped to installed library",
        "Memory skeleton skipped for repo using memory suite",
    ],
    "prune-skill": [
        "Technique pruned because no disproving paper found",
        "Newer publication assumed better without evidence check",
        "Entire concept deleted instead of obsolete instruction line",
        "Prune executed before secure-* scan of target skill",
    ],
    "publish-skill": [
        "Directory name mismatches frontmatter name field",
        "Hardcoded local paths left in scripts or examples",
        "Publish attempted before full secure-* library sweep",
        "Scripts contain internal URLs or machine-specific paths",
    ],
    "reality-check": [
        "Capability claim scored without repo or runtime evidence",
        "Empty registry or template-only file treated as working",
        "README aspirational diagram taken as implemented flow",
        "Verdict issued without checking negative signals first",
    ],
    "research-skill": [
        "Training knowledge reported as sourced finding",
        "External source used before secure-* SAFE clearance",
        "Repo skills ignored as highest-value pattern source",
        "No practitioner source when academic literature empty",
    ],
    "retroactive-project-setup": [
        "Write-allowlist violated — files changed outside contract",
        "Inferred fact written as certain without confirm tag",
        "Architecture doc reimplemented instead of orchestrating",
        "Synthetic handoff missing git hash and branch state",
    ],
    "second-order": [
        "Only first-order benefits listed for the decision",
        "Competitor response not modeled for strategic move",
        "Human behavior change assumed instant not resisted",
        "Consequence chain stops at one hop",
    ],
    "secure-skill": [
        "Partial file scan — content after line 400 skipped",
        "Obfuscation finding downgraded below CRITICAL",
        "Sub-check skipped because orchestrator already ran once",
        "Capability mismatch with stated skill purpose ignored",
    ],
    "secure-skill-content-sanitization": [
        "Zero-width or homoglyph chars not stripped before scan",
        "HTML comments or hidden CSS text left in sanitized body",
        "Sanitization skipped because source looked like plain markdown",
        "Misleading link text not normalized before downstream use",
    ],
    "secure-skill-repo-ingestion": [
        "Repo example copied into skill without quarantine review",
        "Dependency deep scan skipped for referenced script paths",
        "Poisoned examples directory ingested without isolation",
        "File or path traversal pattern not flagged in ingestion",
    ],
    "secure-skill-runtime": [
        "Skill overwrite attempted from external repo content",
        "Provenance chain missing for approved external item",
        "DoS or state-corruption pattern not enforced at runtime",
        "No-go repo list bypassed for convenience",
    ],
    "setup-evaluation": [
        "Eval run from same agent that built the target — bias",
        "Partial pass reported as acceptable overall pass",
        "Architecture spec missing for complex multi-agent build",
        "Knowledge-gap flags ignored instead of acknowledged",
    ],
    "shipping-and-launch": [
        "Launch without rollback path or previous artifact",
        "Traffic shifted before error and KPI monitors exist",
        "Full rollout for non-trivial change without canary",
        "Staging-only validation at fraction of prod data volume",
    ],
    "skill-deconflict": [
        "learn-from family treated as duplicate instead of orchestrator",
        "inversion and adversarial-hat merged as same capability",
        "Generic word overlap flagged without full phrase match",
        "Deconflict report missing recommended survivor skill",
    ],
    "skill-finder": [
        "Match chosen from name similarity not description purpose",
        "Partial overlap misread as full capability coverage",
        "No-match not returned when library truly lacks fit",
        "Called skill recommended without reading full SKILL.md",
    ],
    "skill-routing": [
        "Ambiguous review routed without disambiguating code vs UI",
        "Plan request sent to wrong planner skill for intent",
        "Non-invocable label returned instead of concrete skill name",
        "Multiple candidates returned without disambiguation step",
    ],
    "socratic": [
        "User's surface question answered before probing",
        "Short answer accepted without one deeper follow-up",
        "Socratic used for simple binary decision",
        "Session ends without surfacing deepest unresolved question",
    ],
    "source-driven-development": [
        "API choice made from training data not fetched docs",
        "Entire docs site fetched instead of one decision page",
        "Deprecated API used because snippet was memorable",
        "Version in code mismatches version cited from docs",
    ],
    "spec-crosscheck": [
        "PASS taken as proof implementation is correct",
        "Constitutional waiver applied without documented approval",
        "Spec or plan edited during read-only crosscheck",
        "Approved status assumed while Needs Clarification remains",
    ],
    "spec-driven-development": [
        "Router writes constitution or spec content directly",
        "Tactical bug fix forced through full SDD pipeline",
        "Ambiguous SDD request starts at wrong phase",
        "Child skill skipped for explicit slash command route",
    ],
    "split-skill": [
        "New child skill created without checking absorption fit",
        "Split performed on secure-* skill via compress path",
        "Pipeline stage split breaking shared step context",
        "Post-split line counts not verified under 200",
    ],
    "technical-debt-audit": [
        "TODO count reported without weighting by risk area",
        "Cosmetic debt overweighted versus structural coupling",
        "Roadmap says refactor everything without time boxes",
        "Authentication or payment HACK deprioritized as cosmetic",
    ],
    "test-driven-development": [
        "Production code with no corresponding test",
        "Test passes on first run (may not test what you think)",
        "Bug fix without a reproduction test",
        "Test names that don't describe behavior",
    ],
    "tool-finder": [
        "Built-in Read Write Grep Bash flagged as missing tools",
        "MCP availability assumed same across all platforms",
        "Globally installed CLI assumed available in sandbox",
        "Tool recommendation without verifying platform constraints",
    ],
    "universal-skill-creator": [
        "SKILL.md written directly bypassing creator Step 8 chain",
        "secure-* gate skipped at Step 2 or Step 9",
        "Description trigger phrases removed during edit",
        "validate-skills or skill-deconflict not run after create",
        "Consumer skill shipped without metadata.origin: project-local",
    ],
    "svg-creation": [
        "<script> or event handlers inside generated SVG",
        "CSS animation shipped for img or README context",
        "Guessed stroke-dasharray on line-draw animation",
        "Morph paths with mismatched command counts",
    ],
    "validate-skills": [
        "agentskills validate run on file not skill directory",
        "secure-* skill sent to compress-skill instead of split-only",
        "Score ≤5/14 flagged but deprecate-skill not suggested",
        "Security library sweep Step 4b skipped on full validate",
    ],
    "venture-exploration": [
        "idea-evaluation loop exceeds three cycles without surfacing",
        "Segment size accepted on trust me without evidence",
        "product-soul invoked before strategic concept survives eval",
        "Kill from evaluation ignored to keep exploring same idea",
    ],
}
