#!/usr/bin/env python
"""H-1g multi-agent shadow run (propose-only, C-1.*: no mocked candidates).

Runs the FULL specialist team (real Gemini calls via run_agent_call, real
Grafana MCP read-only tools, real verifier, real leverage synthesis) over
seeded Stage-1 failure scenarios, persists REAL pc-deliberations documents,
and writes a real Grafana annotation per cycle. Nothing executes: ranked
actions stay proposals in the record (H-0b owns ACT mode).

Scenario inputs are the labeled synthetic Stage-1 failure fixtures from
backend/evals/datasets/reliability_root_cause.jsonl (C-1.3 — synthetic
INPUT data is allowed; faked functionality is not). The delivery scenario's
QC report is generated by the REAL D-4 evaluator (evaluate_delivery) on a
labeled synthetic probe — not a hand-written report.

Evidence: docs/evidence/H-1/shadow_run_<date>.jsonl + shadow_run_<date>_summary.json
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.core.config import get_settings
from backend.core.firestore import get_firestore
from backend.jobs.models import utc_now_iso
from backend.stations.delivery.evaluate import evaluate_delivery
from backend.supervisor.agents.delivery_qc import investigate as qc_investigate
from backend.supervisor.agents.reliability_investigator import (
    investigate as reliability_investigate,
)
from backend.supervisor.agents.reliability_investigator import (
    read_only_grafana_tools,
)
from backend.supervisor.agents.spend_guardian import investigate as spend_investigate
from backend.supervisor.agents.verification import verify as verify_verdict
from backend.supervisor.deliberation import DELIBERATIONS, run_deliberation_cycle

DATASET = ROOT / "backend" / "evals" / "datasets" / "reliability_root_cause.jsonl"
EVIDENCE = ROOT / "docs" / "evidence" / "H-1"
JOBS = "pc-jobs"
PROJECTS = "pc-projects"


def scenario_job_doc(row: dict, project_id: str) -> dict:
    """Job doc for the shadow run: the dataset row's real Stage-1 failure
    payload. The delivery row's QC report is produced by the real D-4
    evaluator on a labeled synthetic probe (4:3 master vs 16:9 profile)."""
    job = dict(row["job"])
    result = dict(job.get("result") or {})
    if row["station"] == "delivery":
        # Labeled synthetic probe input (C-1.3): 1440x1080 4:3 master.
        probe = {
            "format": "mov,mp4,m4a,3gp,3g2,mj2",
            "codec": "h264",
            "width": 1440,
            "height": 1080,
            "fps": 24.0,
            "bit_rate": 12_000_000,
        }
        result["delivery"] = evaluate_delivery(
            destination="streaming",
            probe=probe,
            lufs=-15.8,
            caption_text="1\n00:00:01,000 --> 00:00:03,000\nReal cue for the shadow run.\n",
            caption_name="captions.srt",
        )
        result["lufs"] = -15.8
    return {
        "id": f"shadow-{row['case_id']}",
        "job_id": f"shadow-{row['case_id']}",
        "station": job["station"],
        "project_id": project_id,
        "input_refs": list(job.get("input_refs") or []),
        "status": job["status"],
        "attempts": job["attempts"],
        "cost_micros": job["cost_micros"],
        "error": job["error"],
        "created_at": utc_now_iso(),
        "updated_at": utc_now_iso(),
        "result": result,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--project",
        default=f"proj-shadow-h1g-{utc_now_iso()[:10].replace('-', '')}",
        help="shadow project id (real pc-projects doc)",
    )
    parser.add_argument("--only", default=None, help="run a single scenario case_id")
    args = parser.parse_args()

    settings = get_settings()
    store = get_firestore(settings)
    project_id = args.project
    if store.get_doc(PROJECTS, project_id) is None:
        store.set_doc(
            PROJECTS,
            project_id,
            {
                "project_id": project_id,
                "title": "H-1g shadow run (propose-only)",
                "created_at": utc_now_iso(),
            },
        )

    rows = [
        json.loads(line)
        for line in DATASET.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    if args.only:
        rows = [row for row in rows if row["case_id"] == args.only]

    # One shared read-only Grafana MCP session for the run (C-2.1: the
    # connector hands specialists only the read-only allowlist).
    from backend.supervisor.mcp import GrafanaMcpConnector, build_server_config

    connector = GrafanaMcpConnector(build_server_config(settings))
    mcp_ok = True
    tools_bound = 0
    try:
        connector.__enter__()
        tools_bound = len(read_only_grafana_tools(connector))
    except Exception as exc:  # MCP down: run without live telemetry, record it.
        print(
            f"MCP connector unavailable ({type(exc).__name__}: {exc}); continuing without."
        )
        mcp_ok = False

    def make_specialists(row: dict):
        """Per-scenario specialist wiring. The Spend Guardian judges the plan
        under judgment: for runaway/spend triggers that is the pending requeue
        the sweeper would issue — estimated at the job's REAL per-attempt
        average cost (no invented numbers)."""

        def specialists_map(name: str, case):
            if name == "reliability_investigator":
                return reliability_investigate(
                    case, settings, connector=connector if mcp_ok else None
                )
            if name == "delivery_qc":
                return qc_investigate(
                    case,
                    settings,
                    store=store,
                    jobs_collection=JOBS,
                    connector=connector if mcp_ok else None,
                ).finding
            if name == "spend_guardian":
                job = case.evidence.get("job") or {}
                proposal = None
                if row["kind"] in ("runaway", "spend_breach", "daily_budget"):
                    attempts = max(1, int(job.get("attempts") or 1))
                    proposal = {
                        "command_name": "retry_job",
                        "args": {"job_id": job.get("id")},
                        # real per-attempt average from the job doc
                        "cost_estimate_micros": int(job.get("cost_micros") or 0)
                        // attempts,
                    }
                return spend_investigate(
                    case,
                    settings,
                    store=store,
                    jobs_collection=JOBS,
                    connector=connector if mcp_ok else None,
                    proposal=proposal,
                ).finding
            raise ValueError(f"no real specialist wired for {name}")

        return specialists_map

    def verifier(case, findings):
        return verify_verdict(
            case, findings, settings, connector=connector if mcp_ok else None
        )

    def annotator(text: str, tags: list[str]) -> dict:
        from backend.supervisor.mcp import GrafanaMcpConnector, build_server_config

        with GrafanaMcpConnector(build_server_config(settings)) as one_shot:
            return one_shot.add_annotation(text, tags=tags)

    records: list[dict] = []
    for row in rows:
        doc = scenario_job_doc(row, project_id)
        store.set_doc(JOBS, doc["id"], doc)
        trigger = {
            "kind": row["kind"],
            "job_id": doc["id"],
            "project_id": project_id,
            "station": row["station"],
        }
        record_row: dict = {
            "scenario": row["case_id"],
            "job_id": doc["id"],
            "trigger_kind": row["kind"],
        }
        try:
            record: dict = {}
            for attempt_no in range(4):  # Vertex 429 wall: backoff and retry
                try:
                    record = asyncio.run(
                        run_deliberation_cycle(
                            trigger,
                            settings,
                            store=store,
                            jobs_collection=JOBS,
                            deliberation_col=DELIBERATIONS,
                            specialists={
                                "reliability_investigator": make_specialists(row),
                                "delivery_qc": make_specialists(row),
                                "spend_guardian": make_specialists(row),
                            },
                            verifier=verifier,
                            annotator=annotator,
                            propose=True,  # propose-only: nothing executes
                        )
                    )
                    break
                except Exception as exc:
                    status = getattr(exc, "code", None) or getattr(
                        exc, "status_code", None
                    )
                    if attempt_no < 3 and (status == 429 or "429" in str(exc)):
                        wait = 60 * (attempt_no + 1)
                        print(
                            f"429 from Vertex; backing off {wait}s (retry {attempt_no + 1}/3)"
                        )
                        import time

                        time.sleep(wait)
                        continue
                    raise
            if not record:
                raise RuntimeError(
                    "deliberation cycle produced no record after retries"
                )
            persisted = store.get_doc(DELIBERATIONS, record["cycle_id"]) is not None
            record_row.update(
                {
                    "ok": True,
                    "cycle_id": record["cycle_id"],
                    "case_id": record["case_id"],
                    "routed_specialists": record["specialists"],
                    "persisted": persisted,
                    "findings": [
                        {
                            "specialist": f["specialist"],
                            "claims": len(f["claims"]),
                            "commands": [
                                a["command_name"] for a in f["proposed_actions"]
                            ],
                        }
                        for f in record["findings"]
                    ],
                    "vetoed": record["verdict"]["rejected"],
                    "approved_specialists": record["verdict"]["approved_specialists"],
                    "ranked_actions": [
                        {
                            "command_name": a["command_name"],
                            "cost_estimate_micros": a["cost_estimate_micros"],
                            "leverage": a["leverage"],
                            "specialist": a["specialist"],
                        }
                        for a in record["recommendation"]["ranked_actions"]
                    ],
                    "status": record["status"],
                }
            )
        except Exception as exc:
            record_row.update({"ok": False, "error": f"{type(exc).__name__}: {exc}"})
        records.append(record_row)
        print(json.dumps(record_row, indent=2))

    if mcp_ok:
        connector.__exit__(None, None, None)

    ok = [r for r in records if r.get("ok")]
    summary = {
        "run": "H-1g shadow run (propose-only)",
        "project_id": project_id,
        "mcp_connector_used": mcp_ok,
        "read_only_tools_bound": tools_bound,
        "scenarios": len(records),
        "cycles_completed": len(ok),
        "all_persisted": all(r.get("persisted") for r in ok) if ok else False,
        "cycles_with_veto": sum(1 for r in ok if r.get("vetoed")),
        "cycles_with_ranked_actions": sum(1 for r in ok if r.get("ranked_actions")),
        "nothing_executed": True,
    }
    EVIDENCE.mkdir(parents=True, exist_ok=True)
    stamp = utc_now_iso()[:10]
    (EVIDENCE / f"shadow_run_{stamp}.jsonl").write_text(
        "\n".join(json.dumps(r) for r in records) + "\n", encoding="utf-8"
    )
    (EVIDENCE / f"shadow_run_{stamp}_summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )
    print(json.dumps(summary, indent=2))
    return 0 if ok and summary["all_persisted"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
